import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';
import type { MusicTrackId } from '@/types';

export type SfxName =
  | 'move'
  | 'capture'
  | 'check'
  | 'checkmate'
  | 'promote'
  | 'click'
  | 'gameStart'
  | 'draw'
  | 'gold'
  | 'shopOpen'
  | 'spellBuy'
  | 'spellExplosion'
  | 'spellTeleport'
  | 'spellShield'
  | 'spellLeap';

/**
 * Synthesized placeholder SFX generated by scripts/generate-sounds.js (see docs/ASSETS_TODO.md
 * for the real sound-design pass planned for a later update).
 */
const SFX_SOURCES: Record<SfxName, number> = {
  move: require('../../assets/sounds/move.wav'),
  capture: require('../../assets/sounds/capture.wav'),
  check: require('../../assets/sounds/check.wav'),
  checkmate: require('../../assets/sounds/checkmate.wav'),
  promote: require('../../assets/sounds/promote.wav'),
  click: require('../../assets/sounds/click.wav'),
  gameStart: require('../../assets/sounds/game_start.wav'),
  draw: require('../../assets/sounds/draw.wav'),
  gold: require('../../assets/sounds/gold.wav'),
  shopOpen: require('../../assets/sounds/shop_open.wav'),
  spellBuy: require('../../assets/sounds/spell_buy.wav'),
  spellExplosion: require('../../assets/sounds/spell_explosion.wav'),
  spellTeleport: require('../../assets/sounds/spell_teleport.wav'),
  spellShield: require('../../assets/sounds/spell_shield.wav'),
  spellLeap: require('../../assets/sounds/spell_leap.wav'),
};

const MUSIC_SOURCES: Record<MusicTrackId, number> = {
  taverne: require('../../assets/sounds/music_taverne.wav'),
  epique: require('../../assets/sounds/music_epique.wav'),
  mystique: require('../../assets/sounds/music_mystique.wav'),
};

let sfxPlayers: Partial<Record<SfxName, AudioPlayer>> | null = null;
let musicPlayer: AudioPlayer | null = null;
let currentMusicTrack: MusicTrackId | null = null;
let audioModeConfigured = false;

function getSfxPlayers(): Partial<Record<SfxName, AudioPlayer>> {
  if (!sfxPlayers) {
    sfxPlayers = {};
    (Object.keys(SFX_SOURCES) as SfxName[]).forEach((name) => {
      try {
        sfxPlayers![name] = createAudioPlayer(SFX_SOURCES[name]);
      } catch (error) {
        console.error('[audio] failed to create player for', name, error);
      }
    });
  }
  return sfxPlayers;
}

export async function initAudio(): Promise<void> {
  if (audioModeConfigured) return;
  try {
    await setAudioModeAsync({ playsInSilentMode: true });
    audioModeConfigured = true;
  } catch (error) {
    console.error('[audio] failed to configure audio mode', error);
  }
}

export function playSfx(name: SfxName, enabled: boolean): void {
  if (!enabled) return;
  try {
    const player = getSfxPlayers()[name];
    if (!player) return;
    player.seekTo(0);
    player.play();
  } catch (error) {
    console.error('[audio] failed to play sfx', name, error);
  }
}

function ensureMusicPlayer(track: MusicTrackId): AudioPlayer {
  if (musicPlayer && currentMusicTrack === track) return musicPlayer;
  musicPlayer?.release();
  musicPlayer = createAudioPlayer(MUSIC_SOURCES[track]);
  musicPlayer.loop = true;
  musicPlayer.volume = 0.32;
  currentMusicTrack = track;
  return musicPlayer;
}

export function playMusic(enabled: boolean, track: MusicTrackId): void {
  if (!enabled) return;
  try {
    const player = ensureMusicPlayer(track);
    player.play();
  } catch (error) {
    console.error('[audio] failed to play music', error);
  }
}

export function stopMusic(): void {
  try {
    musicPlayer?.pause();
  } catch (error) {
    console.error('[audio] failed to stop music', error);
  }
}

export function setMusicEnabled(enabled: boolean, track: MusicTrackId): void {
  if (enabled) playMusic(true, track);
  else stopMusic();
}

/** Switches to a different track, preserving playback state (keeps playing if already playing). */
export function setMusicTrack(track: MusicTrackId, enabled: boolean): void {
  const wasPlaying = musicPlayer?.playing ?? false;
  if (track === currentMusicTrack && musicPlayer) return;
  const player = ensureMusicPlayer(track);
  if (enabled && wasPlaying) player.play();
}

export function releaseAllAudio(): void {
  Object.values(sfxPlayers ?? {}).forEach((player) => player?.release());
  musicPlayer?.release();
  sfxPlayers = null;
  musicPlayer = null;
  currentMusicTrack = null;
}
