import { createAudioPlayer, createAudioPlaylist, setAudioModeAsync, type AudioPlayer, type AudioPlaylist } from 'expo-audio';

export type SfxName =
  | 'move'
  | 'capture'
  | 'check'
  | 'checkmate'
  | 'promote'
  | 'click'
  | 'gameStart'
  | 'draw'
  | 'gold'
  | 'shopOpen'
  | 'spellBuy'
  | 'spellExplosion'
  | 'spellTeleport'
  | 'spellShield'
  | 'spellLeap';

/**
 * Synthesized placeholder SFX generated by scripts/generate-sounds.js (see docs/ASSETS_TODO.md
 * for the real sound-design pass planned for a later update).
 */
const SFX_SOURCES: Record<SfxName, number> = {
  move: require('../../assets/sounds/move.wav'),
  capture: require('../../assets/sounds/capture.wav'),
  check: require('../../assets/sounds/check.wav'),
  checkmate: require('../../assets/sounds/checkmate.wav'),
  promote: require('../../assets/sounds/promote.wav'),
  click: require('../../assets/sounds/click.wav'),
  gameStart: require('../../assets/sounds/game_start.wav'),
  draw: require('../../assets/sounds/draw.wav'),
  gold: require('../../assets/sounds/gold.wav'),
  shopOpen: require('../../assets/sounds/shop_open.wav'),
  spellBuy: require('../../assets/sounds/spell_buy.wav'),
  spellExplosion: require('../../assets/sounds/spell_explosion.wav'),
  spellTeleport: require('../../assets/sounds/spell_teleport.wav'),
  spellShield: require('../../assets/sounds/spell_shield.wav'),
  spellLeap: require('../../assets/sounds/spell_leap.wav'),
};

/** Menu/lobby screens loop this single track. */
const MENU_MUSIC_SOURCE = require('../../assets/music/menu.mp3');

/**
 * In-match music: starts on the "match start" track; if a game runs long enough for it to finish,
 * the tavern tracks continue the playlist back-to-back, then the whole sequence loops.
 */
const MATCH_MUSIC_SOURCES = [
  require('../../assets/music/match_start.mp3'),
  require('../../assets/music/tavern_1.mp3'),
  require('../../assets/music/tavern_2.mp3'),
];

export type MusicContext = 'menu' | 'match';

let sfxPlayers: Partial<Record<SfxName, AudioPlayer>> | null = null;
let menuPlayer: AudioPlayer | null = null;
let matchPlaylist: AudioPlaylist | null = null;
let activeMusicContext: MusicContext | null = null;
let audioModeConfigured = false;

function getSfxPlayers(): Partial<Record<SfxName, AudioPlayer>> {
  if (!sfxPlayers) {
    sfxPlayers = {};
    (Object.keys(SFX_SOURCES) as SfxName[]).forEach((name) => {
      try {
        sfxPlayers![name] = createAudioPlayer(SFX_SOURCES[name]);
      } catch (error) {
        console.error('[audio] failed to create player for', name, error);
      }
    });
  }
  return sfxPlayers;
}

function getMenuPlayer(): AudioPlayer {
  if (!menuPlayer) {
    menuPlayer = createAudioPlayer(MENU_MUSIC_SOURCE);
    menuPlayer.loop = true;
  }
  return menuPlayer;
}

function getMatchPlaylist(): AudioPlaylist {
  if (!matchPlaylist) {
    matchPlaylist = createAudioPlaylist({ sources: MATCH_MUSIC_SOURCES });
    matchPlaylist.loop = 'all';
  }
  return matchPlaylist;
}

export async function initAudio(): Promise<void> {
  if (audioModeConfigured) return;
  try {
    await setAudioModeAsync({ playsInSilentMode: true });
    audioModeConfigured = true;
  } catch (error) {
    console.error('[audio] failed to configure audio mode', error);
  }
}

export function playSfx(name: SfxName, enabled: boolean): void {
  if (!enabled) return;
  try {
    const player = getSfxPlayers()[name];
    if (!player) return;
    player.seekTo(0);
    player.play();
  } catch (error) {
    console.error('[audio] failed to play sfx', name, error);
  }
}

/**
 * Switches to (or resumes) the given music context. Switching context always restarts that
 * context's music from its first track; re-selecting the already-active context just resyncs
 * volume/enabled without interrupting playback.
 */
export function setMusicContext(context: MusicContext, enabled: boolean, volume: number): void {
  if (activeMusicContext === context) {
    if (context === 'menu') {
      const player = getMenuPlayer();
      player.volume = volume;
      if (enabled) player.play();
      else player.pause();
    } else {
      const playlist = getMatchPlaylist();
      playlist.volume = volume;
      if (enabled) playlist.play();
      else playlist.pause();
    }
    return;
  }

  try {
    menuPlayer?.pause();
  } catch {
    // ignore
  }
  try {
    matchPlaylist?.pause();
  } catch {
    // ignore
  }
  activeMusicContext = context;

  try {
    if (context === 'menu') {
      const player = getMenuPlayer();
      player.volume = volume;
      void player.seekTo(0);
      if (enabled) player.play();
    } else {
      const playlist = getMatchPlaylist();
      playlist.volume = volume;
      playlist.skipTo(0);
      if (enabled) playlist.play();
    }
  } catch (error) {
    console.error('[audio] failed to start music context', context, error);
  }
}

/** Live volume update, applied to whichever context is currently active (and cached for later). */
export function setMusicVolume(volume: number): void {
  if (menuPlayer) menuPlayer.volume = volume;
  if (matchPlaylist) matchPlaylist.volume = volume;
}

/** Mute/unmute without restarting or losing playback position. */
export function setMusicEnabled(enabled: boolean): void {
  try {
    if (activeMusicContext === 'menu') {
      if (enabled) menuPlayer?.play();
      else menuPlayer?.pause();
    } else if (activeMusicContext === 'match') {
      if (enabled) matchPlaylist?.play();
      else matchPlaylist?.pause();
    }
  } catch (error) {
    console.error('[audio] failed to toggle music', error);
  }
}

export function stopMusic(): void {
  try {
    menuPlayer?.pause();
    matchPlaylist?.pause();
    activeMusicContext = null;
  } catch (error) {
    console.error('[audio] failed to stop music', error);
  }
}

export function releaseAllAudio(): void {
  Object.values(sfxPlayers ?? {}).forEach((player) => player?.remove());
  menuPlayer?.remove();
  matchPlaylist?.destroy();
  sfxPlayers = null;
  menuPlayer = null;
  matchPlaylist = null;
  activeMusicContext = null;
}
